from datetime import datetime
from typing import Optional
from pydantic import BaseModel

# Pydantic models define the shape of JSON going IN and OUT of the API.
# FastAPI uses these to validate requests and serialize responses automatically.


# ── Chat ──────────────────────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    session_id: str     # UUID generated by the frontend — identifies the conversation
    message: str        # the customer's question


class SourceChunk(BaseModel):
    file: str
    excerpt: str
    score: float


class ChatResponse(BaseModel):
    answer: str
    confidence: float           # 0.0 (no idea) → 1.0 (very confident)
    escalated: bool             # True if flagged for human review
    escalation_reason: Optional[str] = None
    sources: list[SourceChunk]  # document chunks used to answer


# ── Conversations (admin) ─────────────────────────────────────────────────────

class MessageOut(BaseModel):
    id: int
    role: str
    content: str
    confidence: Optional[float]
    created_at: datetime

    class Config:
        from_attributes = True   # allows building from SQLAlchemy model objects


class ConversationOut(BaseModel):
    id: str
    created_at: datetime
    is_escalated: bool
    resolved: bool
    messages: list[MessageOut]

    class Config:
        from_attributes = True


# ── Escalations (admin) ───────────────────────────────────────────────────────

class EscalationOut(BaseModel):
    id: int
    conversation_id: str
    reason: str
    resolved: bool
    resolved_at: Optional[datetime]
    admin_notes: Optional[str]
    created_at: datetime

    class Config:
        from_attributes = True


class ResolveRequest(BaseModel):
    admin_notes: Optional[str] = None   # optional note when resolving


# ── Document upload (admin) ───────────────────────────────────────────────────

class UploadResponse(BaseModel):
    filename: str
    chunks_added: int
    message: str
